export default {
    "raichu": {
        "national_pokedex_id": 26,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Raichu",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "clefable": {
        "national_pokedex_id": 36,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Clefable",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "golduck": {
        "national_pokedex_id": 55,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Golduck",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "alakazam": {
        "national_pokedex_id": 65,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Alakazam",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "machamp": {
        "national_pokedex_id": 68,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Machamp",
        "pokemon_type": ["fighting"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "tentacruel": {
        "national_pokedex_id": 73,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Tentacruel",
        "pokemon_type": ["water", "poison"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "golem": {
        "national_pokedex_id": 76,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Golem",
        "pokemon_type": ["rock", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "rapidash": {
        "national_pokedex_id": 78,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Rapidash",
        "pokemon_type": ["fire"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "rapidash (flash fire)": {
        "national_pokedex_id": 78,
        "region_pokedex_id": 1,
        "variant_id": 0,
        "name": "Rapidash",
        "pokemon_type": ["fire"],
        "ability_weakness_modifier": "flash fire",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "gengar": {
        "national_pokedex_id": 94,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Gengar",
        "pokemon_type": ["ghost", "poison"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "seaking": {
        "national_pokedex_id": 119,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Seaking",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "mr. mime": {
        "national_pokedex_id": 122,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mr. Mime",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "mr. mime (filter)": {
        "national_pokedex_id": 122,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Mr. Mime",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "filter",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "gyarados": {
        "national_pokedex_id": 130,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Gyarados",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "snorlax": {
        "national_pokedex_id": 143,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Snorlax",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "snorlax (thick fat)": {
        "national_pokedex_id": 143,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Snorlax",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "thick fat",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "noctowl": {
        "national_pokedex_id": 164,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Noctowl",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "crobat": {
        "national_pokedex_id": 169,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Crobat",
        "pokemon_type": ["poison", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "azumarill": {
        "national_pokedex_id": 184,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Azumarill",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "azumarill (thick fat)": {
        "national_pokedex_id": 184,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Azumarill",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "thick fat",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "sudowoodo": {
        "national_pokedex_id": 185,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Sudowoodo",
        "pokemon_type": ["rock"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "quagsire": {
        "national_pokedex_id": 195,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Quagsire",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "quagsire (water absorb)": {
        "national_pokedex_id": 195,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Quagsire",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "water absorb",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "unown": {
        "national_pokedex_id": 201,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Gyarados",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "girafarig": {
        "national_pokedex_id": 203,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Girafarig",
        "pokemon_type": ["normal", "psychic"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "steelix": {
        "national_pokedex_id": 206,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Gyarados",
        "pokemon_type": ["steel", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "heracross": {
        "national_pokedex_id": 214,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Heracross",
        "pokemon_type": ["bug", "fighting"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "octillery": {
        "national_pokedex_id": 224,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Octillery",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "mantine": {
        "national_pokedex_id": 226,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mantine",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "mantine (water absorb)": {
        "national_pokedex_id": 226,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Toxicroak",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "water absorb",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "blissey": {
        "national_pokedex_id": 242,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Blissey",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "beautifly": {
        "national_pokedex_id": 267,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mothim",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "dustox": {
        "national_pokedex_id": 269,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mothim",
        "pokemon_type": ["bug", "poison"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "pelipper": {
        "national_pokedex_id": 279,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Pelipper",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "medicham": {
        "national_pokedex_id": 308,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Medicham",
        "pokemon_type": ["fighting", "psychic"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "whiscash": {
        "national_pokedex_id": 340,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Whiscash",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "milotic": {
        "national_pokedex_id": 350,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Milotic",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "true"
    },
    "chimecho": {
        "national_pokedex_id": 358,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Chimecho",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "torterra": {
        "national_pokedex_id": 389,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Torterra",
        "pokemon_type": ["grass", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "infernape": {
        "national_pokedex_id": 392,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Infernape",
        "pokemon_type": ["fire", "fighting"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "empoleon": {
        "national_pokedex_id": 395,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Empoleon",
        "pokemon_type": ["water", "steel"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "staraptor": {
        "national_pokedex_id": 398,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Staraptor",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "bibarel": {
        "national_pokedex_id": 400,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Bibarel",
        "pokemon_type": ["normal", "water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "kricketune": {
        "national_pokedex_id": 402,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Kricketune",
        "pokemon_type": ["bug"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "luxray": {
        "national_pokedex_id": 405,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Luxray",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "roserade": {
        "national_pokedex_id": 407,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Roserade",
        "pokemon_type": ["grass", "poison"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "wormadam (plant cloak)": {
        "national_pokedex_id": 413,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Wormadam",
        "pokemon_type": ["bug", "grass"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "wormadam (sandy cloak)": {
        "national_pokedex_id": 413,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Wormadam",
        "pokemon_type": ["bug", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "wormadam (trash cloak)": {
        "national_pokedex_id": 413,
        "region_pokedex_id": 0,
        "variant_id": 2,
        "name": "Wormadam",
        "pokemon_type": ["bug", "steel"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "mothim": {
        "national_pokedex_id": 414,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mothim",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "vespiquen": {
        "national_pokedex_id": 416,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Vespiquen",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "pachirisu": {
        "national_pokedex_id": 417,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Pachirisu",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "floatzel": {
        "national_pokedex_id": 419,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Floatzel",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "cherrim": {
        "national_pokedex_id": 421,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Cherrim",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "gastrodon": {
        "national_pokedex_id": 423,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Gastrodon",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "ambipom": {
        "national_pokedex_id": 424,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Ambipom",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "drifblim": {
        "national_pokedex_id": 426,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Drifblim",
        "pokemon_type": ["ghost", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "lopunny": {
        "national_pokedex_id": 428,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Lopunny",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "bronzong": {
        "national_pokedex_id": 437,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "bronzong (levitate)": {
        "national_pokedex_id": 437,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "bronzong (heatproof)": {
        "national_pokedex_id": 437,
        "region_pokedex_id": 0,
        "variant_id": 2,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "heatproof",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "chatot": {
        "national_pokedex_id": 441,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Chatot",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "spiritomb": {
        "national_pokedex_id": 442,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Spiritomb",
        "pokemon_type": ["ghost", "dark"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "garchomp": {
        "national_pokedex_id": 445,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Garchomp",
        "pokemon_type": ["dragon", "ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "lucario": {
        "national_pokedex_id": 448,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Lucairo",
        "pokemon_type": ["fighting", "steel"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "hippowdon": {
        "national_pokedex_id": 450,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Hippowdon",
        "pokemon_type": ["ground"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "drapion": {
        "national_pokedex_id": 452,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Drapion",
        "pokemon_type": ["poison", "dark"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "toxicroak": {
        "national_pokedex_id": 454,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Toxicroak",
        "pokemon_type": ["poison", "fighting"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "toxicroak (dry skin)": {
        "national_pokedex_id": 454,
        "region_pokedex_id": 0,
        "variant_id": 1,
        "name": "Toxicroak",
        "pokemon_type": ["poison", "fighting"],
        "ability_weakness_modifier": "dry skin",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "carnivine": {
        "national_pokedex_id": 455,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Carnivine",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "lumineon": {
        "national_pokedex_id": 457,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Lumineon",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "abomasnow": {
        "national_pokedex_id": 460,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Abomasnow",
        "pokemon_type": ["grass", "ice"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "weavile": {
        "national_pokedex_id": 461,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Weavile",
        "pokemon_type": ["dark", "ice"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "false",
        "trade evolution": "false"
    },
    "uxie": {
        "national_pokedex_id": 480,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Uxie",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "true",
        "trade evolution": "false"
    },
    "mesprit": {
        "national_pokedex_id": 481,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Mesprit",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "true",
        "trade evolution": "false"
    },
    "azelf": {
        "national_pokedex_id": 482,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Azelf",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": "all",
        "legendary/mythic": "true",
        "trade evolution": "false"
    },
    "phione": {
        "national_pokedex_id": 489,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Phione",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "true",
        "trade evolution": "false"
    },
    "manaphy": {
        "national_pokedex_id": 490,
        "region_pokedex_id": 0,
        "variant_id": 0,
        "name": "Manaphy",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": "all",
        "legendary/mythic": "true",
        "trade evolution": "false"
    },
};