export default {
    "dppt": {
        "torterra": {
            "region_pokedex_id": 3,
            "national_pokedex_id": 389,
            "variant_id": 0,
            "name": "Torterra",
            "pokemon_type": ["grass", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": true,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "infernape": {
            "region_pokedex_id": 6,
            "national_pokedex_id": 392,
            "variant_id": 0,
            "name": "Infernape",
            "pokemon_type": ["fire", "fighting"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": true,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "empoleon": {
            "region_pokedex_id": 9,
            "national_pokedex_id": 395,
            "variant_id": 0,
            "name": "Empoleon",
            "pokemon_type": ["water", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": true,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "staraptor": {
            "region_pokedex_id": 12,
            "national_pokedex_id": 398,
            "variant_id": 0,
            "name": "Staraptor",
            "pokemon_type": ["normal", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "bibarel": {
            "region_pokedex_id": 14,
            "national_pokedex_id": 400,
            "variant_id": 0,
            "name": "Bibarel",
            "pokemon_type": ["normal", "water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "kricketune": {
            "region_pokedex_id": 16,
            "national_pokedex_id": 402,
            "variant_id": 0,
            "name": "Kricketune",
            "pokemon_type": ["bug"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "luxray": {
            "region_pokedex_id": 19,
            "national_pokedex_id": 405,
            "variant_id": 0,
            "name": "Luxray",
            "pokemon_type": ["electric"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "alakazam": {
            "region_pokedex_id": 22,
            "national_pokedex_id": 65,
            "variant_id": 0,
            "name": "Alakazam",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gyarados": {
            "region_pokedex_id": 24,
            "national_pokedex_id": 130,
            "variant_id": 0,
            "name": "Gyarados",
            "pokemon_type": ["water", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "roserade": {
            "region_pokedex_id": 27,
            "national_pokedex_id": 407,
            "variant_id": 0,
            "name": "Roserade",
            "pokemon_type": ["grass", "poison"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "crobat": {
            "region_pokedex_id": 30,
            "national_pokedex_id": 169,
            "variant_id": 0,
            "name": "Crobat",
            "pokemon_type": ["poison", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "golem": {
            "region_pokedex_id": 33,
            "national_pokedex_id": 76,
            "variant_id": 0,
            "name": "Golem",
            "pokemon_type": ["rock", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "steelix": {
            "region_pokedex_id": 35,
            "national_pokedex_id": 206,
            "variant_id": 0,
            "name": "Steelix",
            "pokemon_type": ["steel", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "rampardos": {
            "region_pokedex_id": 37,
            "national_pokedex_id": 409,
            "variant_id": 0,
            "name": "Rampardos",
            "pokemon_type": ["rock"],
            "ability_weakness_modifier": "none",
            "version": ["diamond", "platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 2,
            "hidden_settings": [false, false, false, false]
        },
        "bastiodon": {
            "region_pokedex_id": 39,
            "national_pokedex_id": 411,
            "variant_id": 0,
            "name": "Bastiodon",
            "pokemon_type": ["rock", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["pearl", "platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 2,
            "hidden_settings": [false, false, false, false]
        },
        "machamp": {
            "region_pokedex_id": 42,
            "national_pokedex_id": 68,
            "variant_id": 0,
            "name": "Machamp",
            "pokemon_type": ["fighting"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "golduck": {
            "region_pokedex_id": 44,
            "national_pokedex_id": 55,
            "variant_id": 0,
            "name": "Golduck",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "wormadam (plant cloak)": {
            "region_pokedex_id": 46,
            "national_pokedex_id": 413,
            "variant_id": 0,
            "name": "Wormadam (Plant Cloak)",
            "pokemon_type": ["bug", "grass"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "wormadam (sandy cloak)": {
            "region_pokedex_id": 46,
            "national_pokedex_id": 413,
            "variant_id": 1,
            "name": "Wormadam (Sandy Cloak)",
            "pokemon_type": ["bug", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "wormadam (trash cloak)": {
            "region_pokedex_id": 46,
            "national_pokedex_id": 413,
            "variant_id": 2,
            "name": "Wormadam (Trash Cloak)",
            "pokemon_type": ["bug", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mothim": {
            "region_pokedex_id": 47,
            "national_pokedex_id": 414,
            "variant_id": 0,
            "name": "Mothim",
            "pokemon_type": ["bug", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "beautifly": {
            "region_pokedex_id": 50,
            "national_pokedex_id": 267,
            "variant_id": 0,
            "name": "Beautifly",
            "pokemon_type": ["bug", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "dustox": {
            "region_pokedex_id": 52,
            "national_pokedex_id": 269,
            "variant_id": 0,
            "name": "Dustox",
            "pokemon_type": ["bug", "poison"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "vespiquen": {
            "region_pokedex_id": 54,
            "national_pokedex_id": 416,
            "variant_id": 0,
            "name": "Vespiquen",
            "pokemon_type": ["bug", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "pachirisu": {
            "region_pokedex_id": 55,
            "national_pokedex_id": 417,
            "variant_id": 0,
            "name": "Pachirisu",
            "pokemon_type": ["electric"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "floatzel": {
            "region_pokedex_id": 57,
            "national_pokedex_id": 419,
            "variant_id": 0,
            "name": "Floatzel",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "cherrim": {
            "region_pokedex_id": 59,
            "national_pokedex_id": 421,
            "variant_id": 0,
            "name": "Cherrim",
            "pokemon_type": ["grass"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gastrodon": {
            "region_pokedex_id": 61,
            "national_pokedex_id": 423,
            "variant_id": 0,
            "name": "Gastrodon",
            "pokemon_type": ["water", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "heracross": {
            "region_pokedex_id": 62,
            "national_pokedex_id": 214,
            "variant_id": 0,
            "name": "Heracross",
            "pokemon_type": ["bug", "fighting"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "ambipom": {
            "region_pokedex_id": 64,
            "national_pokedex_id": 424,
            "variant_id": 0,
            "name": "Ambipom",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "drifblim": {
            "region_pokedex_id": 66,
            "national_pokedex_id": 426,
            "variant_id": 0,
            "name": "Drifblim",
            "pokemon_type": ["ghost", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "lopunny": {
            "region_pokedex_id": 68,
            "national_pokedex_id": 428,
            "variant_id": 0,
            "name": "Lopunny",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gengar": {
            "region_pokedex_id": 71,
            "national_pokedex_id": 94,
            "variant_id": 0,
            "name": "Gengar",
            "pokemon_type": ["ghost", "poison"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mismagius": {
            "region_pokedex_id": 73,
            "national_pokedex_id": 429,
            "variant_id": 0,
            "name": "Mismagius",
            "pokemon_type": ["ghost"],
            "ability_weakness_modifier": "levitate",
            "version": ["pearl"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "honchkrow": {
            "region_pokedex_id": 75,
            "national_pokedex_id": 430,
            "variant_id": 0,
            "name": "Honchkrow",
            "pokemon_type": ["dark", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["diamond"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "purugly": {
            "region_pokedex_id": 77,
            "national_pokedex_id": 432,
            "variant_id": 0,
            "name": "Purugly",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["pearl"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "purugly (thick fat)": {
            "region_pokedex_id": 77,
            "national_pokedex_id": 432,
            "variant_id": 1,
            "name": "Purugly",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "thick fat",
            "version": ["pearl"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "seaking": {
            "region_pokedex_id": 79,
            "national_pokedex_id": 119,
            "variant_id": 0,
            "name": "Seaking",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "whiscash": {
            "region_pokedex_id": 81,
            "national_pokedex_id": 340,
            "variant_id": 0,
            "name": "Whiscash",
            "pokemon_type": ["water", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "chimecho": {
            "region_pokedex_id": 83,
            "national_pokedex_id": 358,
            "variant_id": 0,
            "name": "Chimecho",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "skuntank": {
            "region_pokedex_id": 85,
            "national_pokedex_id": 435,
            "variant_id": 0,
            "name": "Skuntank",
            "pokemon_type": ["poison", "dark"],
            "ability_weakness_modifier": "none",
            "version": ["diamond"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "medicham": {
            "region_pokedex_id": 87,
            "national_pokedex_id": 308,
            "variant_id": 0,
            "name": "Medicham",
            "pokemon_type": ["fighting", "psychic"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "bronzong": {
            "region_pokedex_id": 89,
            "national_pokedex_id": 437,
            "variant_id": 0,
            "name": "Bronzong",
            "pokemon_type": ["steel", "psychic"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "bronzong (levitate)": {
            "region_pokedex_id": 89,
            "national_pokedex_id": 437,
            "variant_id": 1,
            "name": "Bronzong",
            "pokemon_type": ["steel", "psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "bronzong (heatproof)": {
            "region_pokedex_id": 89,
            "national_pokedex_id": 437,
            "variant_id": 2,
            "name": "Bronzong",
            "pokemon_type": ["steel", "psychic"],
            "ability_weakness_modifier": "heatproof",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "rapidash": {
            "region_pokedex_id": 91,
            "national_pokedex_id": 78,
            "variant_id": 0,
            "name": "Rapidash",
            "pokemon_type": ["fire"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        /*
        "rapidash (flash fire)": {
            "region_pokedex_id": 91,
            "national_pokedex_id": 78,
            "variant_id": 1,
            "name": "Rapidash",
            "pokemon_type": ["fire"],
            "ability_weakness_modifier": "flash fire",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        */
        "sudowoodo": {
            "region_pokedex_id": 93,
            "national_pokedex_id": 185,
            "variant_id": 0,
            "name": "Sudowoodo",
            "pokemon_type": ["rock"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mr. mime": {
            "region_pokedex_id": 95,
            "national_pokedex_id": 122,
            "variant_id": 0,
            "name": "Mr. Mime",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "blissey": {
            "region_pokedex_id": 98,
            "national_pokedex_id": 242,
            "variant_id": 0,
            "name": "Blissey",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "clefable": {
            "region_pokedex_id": 101,
            "national_pokedex_id": 36,
            "variant_id": 0,
            "name": "Clefable",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "chatot": {
            "region_pokedex_id": 102,
            "national_pokedex_id": 441,
            "variant_id": 0,
            "name": "Chatot",
            "pokemon_type": ["normal", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "raichu": {
            "region_pokedex_id": 105,
            "national_pokedex_id": 26,
            "variant_id": 0,
            "name": "Raichu",
            "pokemon_type": ["electric"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "noctowl": {
            "region_pokedex_id": 107,
            "national_pokedex_id": 164,
            "variant_id": 0,
            "name": "Noctowl",
            "pokemon_type": ["normal", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "spiritomb": {
            "region_pokedex_id": 108,
            "national_pokedex_id": 442,
            "variant_id": 0,
            "name": "Spiritomb",
            "pokemon_type": ["ghost", "dark"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "garchomp": {
            "region_pokedex_id": 111,
            "national_pokedex_id": 445,
            "variant_id": 0,
            "name": "Garchomp",
            "pokemon_type": ["dragon", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "snorlax": {
            "region_pokedex_id": 113,
            "national_pokedex_id": 143,
            "variant_id": 0,
            "name": "Snorlax",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "snorlax (thick fat)": {
            "region_pokedex_id": 113,
            "national_pokedex_id": 143,
            "variant_id": 1,
            "name": "Snorlax (Thick Fat)",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "thick fat",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "unown": {
            "region_pokedex_id": 114,
            "national_pokedex_id": 201,
            "variant_id": 0,
            "name": "Unown",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "lucario": {
            "region_pokedex_id": 116,
            "national_pokedex_id": 448,
            "variant_id": 0,
            "name": "Lucario",
            "pokemon_type": ["fighting", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "quagsire": {
            "region_pokedex_id": 118,
            "national_pokedex_id": 195,
            "variant_id": 0,
            "name": "Quagsire",
            "pokemon_type": ["water", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "quagsire (water absorb)": {
            "region_pokedex_id": 118,
            "national_pokedex_id": 195,
            "variant_id": 1,
            "name": "Quagsire",
            "pokemon_type": ["water", "ground"],
            "ability_weakness_modifier": "water absorb",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "pelipper": {
            "region_pokedex_id": 120,
            "national_pokedex_id": 279,
            "variant_id": 0,
            "name": "Pelipper",
            "pokemon_type": ["water", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "girafarig": {
            "region_pokedex_id": 121,
            "national_pokedex_id": 203,
            "variant_id": 0,
            "name": "Girafarig",
            "pokemon_type": ["normal", "psychic"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "hippowdon": {
            "region_pokedex_id": 123,
            "national_pokedex_id": 450,
            "variant_id": 0,
            "name": "Hippowdon",
            "pokemon_type": ["ground"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "azumarill": {
            "region_pokedex_id": 126,
            "national_pokedex_id": 184,
            "variant_id": 0,
            "name": "Azumarill",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        /*
        "azumarill (thick fat)": {
            "region_pokedex_id": 126,
            "national_pokedex_id": 184,
            "variant_id": 1,
            "name": "Azumarill",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "thick fat",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        */
        "drapion": {
            "region_pokedex_id": 128,
            "national_pokedex_id": 452,
            "variant_id": 0,
            "name": "Drapion",
            "pokemon_type": ["poison", "dark"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "toxicroak": {
            "region_pokedex_id": 130,
            "national_pokedex_id": 454,
            "variant_id": 0,
            "name": "Toxicroak",
            "pokemon_type": ["poison", "fighting"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "toxicroak (dry skin)": {
            "region_pokedex_id": 130,
            "national_pokedex_id": 454,
            "variant_id": 1,
            "name": "Toxicroak",
            "pokemon_type": ["poison", "fighting"],
            "ability_weakness_modifier": "dry skin",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "carnivine": {
            "region_pokedex_id": 131,
            "national_pokedex_id": 455,
            "variant_id": 0,
            "name": "Carnivine",
            "pokemon_type": ["grass"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "octillery": {
            "region_pokedex_id": 133,
            "national_pokedex_id": 224,
            "variant_id": 0,
            "name": "Octillery",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "lumineon": {
            "region_pokedex_id": 135,
            "national_pokedex_id": 457,
            "variant_id": 0,
            "name": "Lumineon",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "tentacruel": {
            "region_pokedex_id": 137,
            "national_pokedex_id": 73,
            "variant_id": 0,
            "name": "Tentacruel",
            "pokemon_type": ["water", "poison"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "milotic": {
            "region_pokedex_id": 139,
            "national_pokedex_id": 350,
            "variant_id": 0,
            "name": "Milotic",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mantine": {
            "region_pokedex_id": 141,
            "national_pokedex_id": 226,
            "variant_id": 0,
            "name": "Mantine",
            "pokemon_type": ["water", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        /*
        "mantine (water absorb)": {
            "region_pokedex_id": 141,
            "national_pokedex_id": 226,
            "variant_id": 1,
            "name": "Mantine",
            "pokemon_type": ["water", "flying"],
            "ability_weakness_modifier": "water absorb",
            "version": ["all"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        */
        "abomasnow": {
            "region_pokedex_id": 143,
            "national_pokedex_id": 460,
            "variant_id": 0,
            "name": "Abomasnow",
            "pokemon_type": ["grass", "ice"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "weavile": {
            "region_pokedex_id": 145,
            "national_pokedex_id": 461,
            "variant_id": 0,
            "name": "Weavile",
            "pokemon_type": ["dark", "ice"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "uxie": {
            "region_pokedex_id": 146,
            "national_pokedex_id": 480,
            "variant_id": 0,
            "name": "Uxie",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mesprit": {
            "region_pokedex_id": 147,
            "national_pokedex_id": 481,
            "variant_id": 0,
            "name": "Mesprit",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "azelf": {
            "region_pokedex_id": 148,
            "national_pokedex_id": 482,
            "variant_id": 0,
            "name": "Azelf",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "levitate",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "dialga": {
            "region_pokedex_id": 149,
            "national_pokedex_id": 483,
            "variant_id": 0,
            "name": "Dialga",
            "pokemon_type": ["steel", "dragon"],
            "ability_weakness_modifier": "none",
            "version": ["diamond", "platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 2,
            "hidden_settings": [false, false, false, false]
        },
        "palkia": {
            "region_pokedex_id": 150,
            "national_pokedex_id": 484,
            "variant_id": 0,
            "name": "Palkia",
            "pokemon_type": ["water", "dragon"],
            "ability_weakness_modifier": "none",
            "version": ["pearl", "platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 2,
            "hidden_settings": [false, false, false, false]
        },
        "manaphy": {
            "region_pokedex_id": 151,
            "national_pokedex_id": 490,
            "variant_id": 0,
            "name": "Manaphy",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["all"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "rotom": {
            "region_pokedex_id": 152,
            "national_pokedex_id": 479,
            "variant_id": 0,
            "name": "Rotom",
            "pokemon_type": ["electric", "ghost"],
            "ability_weakness_modifier": "levitate",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gliscor": {
            "region_pokedex_id": 154,
            "national_pokedex_id": 472,
            "variant_id": 0,
            "name": "Gliscor",
            "pokemon_type": ["ground", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "probopass": {
            "region_pokedex_id": 156,
            "national_pokedex_id": 476,
            "variant_id": 0,
            "name": "Probopass",
            "pokemon_type": ["rock", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gardevoir": {
            "region_pokedex_id": 159,
            "national_pokedex_id": 282,
            "variant_id": 0,
            "name": "Gardevoir",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "gallade": {
            "region_pokedex_id": 160,
            "national_pokedex_id": 475,
            "variant_id": 0,
            "name": "Gallade",
            "pokemon_type": ["psychic", "fighting"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "lickilicky": {
            "region_pokedex_id": 162,
            "national_pokedex_id": 463,
            "variant_id": 0,
            "name": "Lickilicky",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "vaporeon": {
            "region_pokedex_id": 164,
            "national_pokedex_id": 134,
            "variant_id": 0,
            "name": "Vaporeon",
            "pokemon_type": ["water"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "jolteon": {
            "region_pokedex_id": 165,
            "national_pokedex_id": 135,
            "variant_id": 0,
            "name": "Jolteon",
            "pokemon_type": ["electric"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "flareon": {
            "region_pokedex_id": 166,
            "national_pokedex_id": 136,
            "variant_id": 0,
            "name": "Flareon",
            "pokemon_type": ["fire"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 1,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "espeon": {
            "region_pokedex_id": 167,
            "national_pokedex_id": 196,
            "variant_id": 0,
            "name": "Espeon",
            "pokemon_type": ["psychic"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "umbreon": {
            "region_pokedex_id": 168,
            "national_pokedex_id": 197,
            "variant_id": 0,
            "name": "Umbreon",
            "pokemon_type": ["dark"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "leafeon": {
            "region_pokedex_id": 169,
            "national_pokedex_id": 470,
            "variant_id": 0,
            "name": "Leafeon",
            "pokemon_type": ["grass"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "glaceon": {
            "region_pokedex_id": 170,
            "national_pokedex_id": 471,
            "variant_id": 0,
            "name": "Glaceon",
            "pokemon_type": ["ice"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "altaria": {
            "region_pokedex_id": 172,
            "national_pokedex_id": 334,
            "variant_id": 0,
            "name": "Altaria",
            "pokemon_type": ["dragon", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "togekiss": {
            "region_pokedex_id": 175,
            "national_pokedex_id": 468,
            "variant_id": 0,
            "name": "Togekiss",
            "pokemon_type": ["normal", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "houndoom": {
            "region_pokedex_id": 177,
            "national_pokedex_id": 229,
            "variant_id": 0,
            "name": "Houndoom",
            "pokemon_type": ["dark", "fire"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        /*
        "houndoom (flash fire)": {
            "region_pokedex_id": 177,
            "national_pokedex_id": 229,
            "variant_id": 1,
            "name": "Houndoom",
            "pokemon_type": ["dark", "fire"],
            "ability_weakness_modifier": "flash fire",
            "version": ["platinum"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        */
        "magnezone": {
            "region_pokedex_id": 180,
            "national_pokedex_id": 462,
            "variant_id": 0,
            "name": "Magnezone",
            "pokemon_type": ["electric", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "tangrowth": {
            "region_pokedex_id": 182,
            "national_pokedex_id": 465,
            "variant_id": 0,
            "name": "Tangrowth",
            "pokemon_type": ["grass"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "yanmega": {
            "region_pokedex_id": 184,
            "national_pokedex_id": 469,
            "variant_id": 0,
            "name": "Yanmega",
            "pokemon_type": ["bug", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "tropius": {
            "region_pokedex_id": 185,
            "national_pokedex_id": 357,
            "variant_id": 0,
            "name": "Tropius",
            "pokemon_type": ["grass", "flying"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "rhyperior": {
            "region_pokedex_id": 188,
            "national_pokedex_id": 464,
            "variant_id": 0,
            "name": "Rhyperior",
            "pokemon_type": ["ground", "rock"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "dusknoir": {
            "region_pokedex_id": 191,
            "national_pokedex_id": 477,
            "variant_id": 0,
            "name": "Dusknoir",
            "pokemon_type": ["ghost"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "porygon-z": {
            "region_pokedex_id": 194,
            "national_pokedex_id": 474,
            "variant_id": 0,
            "name": "Porygon-Z",
            "pokemon_type": ["normal"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "scizor": {
            "region_pokedex_id": 196,
            "national_pokedex_id": 212,
            "variant_id": 0,
            "name": "Scizor",
            "pokemon_type": ["bug", "steel"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 2,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "electivire": {
            "region_pokedex_id": 199,
            "national_pokedex_id": 466,
            "variant_id": 0,
            "name": "Electivire",
            "pokemon_type": ["electric"],
            "ability_weakness_modifier": "motor drive",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "magmortar": {
            "region_pokedex_id": 202,
            "national_pokedex_id": 467,
            "variant_id": 0,
            "name": "Magmortar",
            "pokemon_type": ["fire"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": true,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "mamoswine": {
            "region_pokedex_id": 205,
            "national_pokedex_id": 473,
            "variant_id": 0,
            "name": "Mamoswine",
            "pokemon_type": ["ice", "ground"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "glalie": {
            "region_pokedex_id": 207,
            "national_pokedex_id": 362,
            "variant_id": 0,
            "name": "Glalie",
            "pokemon_type": ["ice"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "froslass": {
            "region_pokedex_id": 208,
            "national_pokedex_id": 478,
            "variant_id": 0,
            "name": "Froslass",
            "pokemon_type": ["ice", "ghost"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "absol": {
            "region_pokedex_id": 209,
            "national_pokedex_id": 359,
            "variant_id": 0,
            "name": "Absol",
            "pokemon_type": ["dark"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 3,
            "starter": false,
            "legendary/mythic": false,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "giratina": {
            "region_pokedex_id": 210,
            "national_pokedex_id": 487,
            "variant_id": 0,
            "name": "Giratina",
            "pokemon_type": ["ghost", "dragon"],
            "ability_weakness_modifier": "none",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
        "giratina (origin forme)": {
            "region_pokedex_id": 210,
            "national_pokedex_id": 487,
            "variant_id": 1,
            "name": "Giratina",
            "pokemon_type": ["ghost", "dragon"],
            "ability_weakness_modifier": "levitate",
            "version": ["platinum"],
            "debut_generation": 4,
            "starter": false,
            "legendary/mythic": true,
            "trade_evolution": false,
            "version_setting_value": 1,
            "hidden_settings": [false, false, false, false]
        },
    }
};