export default {
    "raichu": {
        "national_pokedex_id": 26,
        "regional_pokedex_id": [26, "gsc", "rse", "frlg", 105, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Raichu",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "clefable": {
        "national_pokedex_id": 36,
        "regional_pokedex_id": [36, "gsc", "rse", "frlg", 101, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Clefable",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "golduck": {
        "national_pokedex_id": 55,
        "regional_pokedex_id": [55, "gsc", "rse", "frlg", 44, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Golduck",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "alakazam": {
        "national_pokedex_id": 65,
        "regional_pokedex_id": [65, "gsc", "rse", "frlg", 22, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Alakazam",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "machamp": {
        "national_pokedex_id": 68,
        "regional_pokedex_id": [68, "gsc", "rse", "frlg", 42, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Machamp",
        "pokemon_type": ["fighting"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "tentacruel": {
        "national_pokedex_id": 73,
        "regional_pokedex_id": [73, "gsc", "rse", "frlg", 137, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Tentacruel",
        "pokemon_type": ["water", "poison"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "golem": {
        "national_pokedex_id": 76,
        "regional_pokedex_id": [76, "gsc", "rse", "frlg", 33, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Golem",
        "pokemon_type": ["rock", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "rapidash": {
        "national_pokedex_id": 78,
        "regional_pokedex_id": [78, "gsc", "rse", "frlg", 91, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Rapidash",
        "pokemon_type": ["fire"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gengar": {
        "national_pokedex_id": 94,
        "regional_pokedex_id": [94, "gsc", "rse", "frlg", 71, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gengar",
        "pokemon_type": ["ghost", "poison"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "seaking": {
        "national_pokedex_id": 119,
        "regional_pokedex_id": [119, "gsc", "rse", "frlg", 79, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Seaking",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "mr. mime": {
        "national_pokedex_id": 122,
        "regional_pokedex_id": [122, "gsc", "rse", "frlg", 95, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mr. Mime",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gyarados": {
        "national_pokedex_id": 130,
        "regional_pokedex_id": [130, "gsc", "rse", "frlg", 24, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gyarados",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "vaporeon": {
        "national_pokedex_id": 134,
        "regional_pokedex_id": [134, "gsc", "rse", "frlg", 164, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Vaporeon",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "jolteon": {
        "national_pokedex_id": 135,
        "regional_pokedex_id": [135, "gsc", "rse", "frlg", 165, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Jolteon",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "flareon": {
        "national_pokedex_id": 136,
        "regional_pokedex_id": [136, "gsc", "rse", "frlg", 166, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Flareon",
        "pokemon_type": ["fire"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "snorlax": {
        "national_pokedex_id": 143,
        "regional_pokedex_id": [143, "gsc", "rse", "frlg", 113, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Snorlax",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "snorlax (thick fat)": {
        "national_pokedex_id": 143,
        "regional_pokedex_id": [143, "gsc", "rse", "frlg", 113, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Snorlax (Thick Fat)",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "thick fat",
        "version": ["all"],
        "debut_generation": 1,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "noctowl": {
        "national_pokedex_id": 164,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 107, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Noctowl",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "crobat": {
        "national_pokedex_id": 169,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 30, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Crobat",
        "pokemon_type": ["poison", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "azumarill": {
        "national_pokedex_id": 184,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 126, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Azumarill",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "sudowoodo": {
        "national_pokedex_id": 185,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 93, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Sudowoodo",
        "pokemon_type": ["rock"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "quagsire": {
        "national_pokedex_id": 195,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 118, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Quagsire",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "quagsire (water absorb)": {
        "national_pokedex_id": 195,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 118, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Quagsire",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "water absorb",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "espeon": {
        "national_pokedex_id": 196,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 167, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Espeon",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "umbreon": {
        "national_pokedex_id": 197,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 168, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Umbreon",
        "pokemon_type": ["dark"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "unown": {
        "national_pokedex_id": 201,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 114, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Unown",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "girafarig": {
        "national_pokedex_id": 203,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 121, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Girafarig",
        "pokemon_type": ["normal", "psychic"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "steelix": {
        "national_pokedex_id": 208,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 35, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Steelix",
        "pokemon_type": ["steel", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "scizor": {
        "national_pokedex_id": 212,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 196, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Scizor",
        "pokemon_type": ["bug", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "heracross": {
        "national_pokedex_id": 214,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 62, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Heracross",
        "pokemon_type": ["bug", "fighting"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "octillery": {
        "national_pokedex_id": 224,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 133, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Octillery",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "mantine": {
        "national_pokedex_id": 226,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 141, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mantine",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "houndoom": {
        "national_pokedex_id": 229,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 177, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Houndoom",
        "pokemon_type": ["dark", "fire"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "blissey": {
        "national_pokedex_id": 242,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 98, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Blissey",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 2,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "beautifly": {
        "national_pokedex_id": 267,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 50, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Beautifly",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "dustox": {
        "national_pokedex_id": 269,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 52, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Dustox",
        "pokemon_type": ["bug", "poison"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "pelipper": {
        "national_pokedex_id": 279,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 120, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Pelipper",
        "pokemon_type": ["water", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gardevoir": {
        "national_pokedex_id": 282,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 159, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gardevoir",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "medicham": {
        "national_pokedex_id": 308,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 87, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Medicham",
        "pokemon_type": ["fighting", "psychic"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "altaria": {
        "national_pokedex_id": 334,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 172, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Altaria",
        "pokemon_type": ["dragon", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "whiscash": {
        "national_pokedex_id": 340,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 81, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Whiscash",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "milotic": {
        "national_pokedex_id": 350,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 139, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Milotic",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "tropius": {
        "national_pokedex_id": 357,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 185, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Tropius",
        "pokemon_type": ["grass", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "chimecho": {
        "national_pokedex_id": 358,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 83, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Chimecho",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "absol": {
        "national_pokedex_id": 359,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 209, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Absol",
        "pokemon_type": ["dark"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "glalie": {
        "national_pokedex_id": 362,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 207, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Glalie",
        "pokemon_type": ["ice"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 3,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "torterra": {
        "national_pokedex_id": 389,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 3, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Torterra",
        "pokemon_type": ["grass", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": true,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "infernape": {
        "national_pokedex_id": 392,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 6, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Infernape",
        "pokemon_type": ["fire", "fighting"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": true,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "empoleon": {
        "national_pokedex_id": 395,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 9, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Empoleon",
        "pokemon_type": ["water", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": true,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "staraptor": {
        "national_pokedex_id": 398,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 12, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Staraptor",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "bibarel": {
        "national_pokedex_id": 400,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 14, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Bibarel",
        "pokemon_type": ["normal", "water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "kricketune": {
        "national_pokedex_id": 402,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 16, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Kricketune",
        "pokemon_type": ["bug"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "luxray": {
        "national_pokedex_id": 405,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 19, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Luxray",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "roserade": {
        "national_pokedex_id": 407,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 27, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Roserade",
        "pokemon_type": ["grass", "poison"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "rampardos": {
        "national_pokedex_id": 409,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 37, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Rampardos",
        "pokemon_type": ["rock"],
        "ability_weakness_modifier": "none",
        "version": ["diamond", "platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 2,
        "hidden_settings": [false, false, false, false]
    },
    "bastiodon": {
        "national_pokedex_id": 411,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 39, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Bastiodon",
        "pokemon_type": ["rock", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["pearl", "platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 2,
        "hidden_settings": [false, false, false, false]
    },
    "wormadam (plant cloak)": {
        "national_pokedex_id": 413,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 46, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Wormadam (Plant Cloak)",
        "pokemon_type": ["bug", "grass"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "wormadam (sandy cloak)": {
        "national_pokedex_id": 413,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 46, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Wormadam (Sandy Cloak)",
        "pokemon_type": ["bug", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "wormadam (trash cloak)": {
        "national_pokedex_id": 413,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 46, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 2,
        "name": "Wormadam (Trash Cloak)",
        "pokemon_type": ["bug", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "mothim": {
        "national_pokedex_id": 414,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 47, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mothim",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "vespiquen": {
        "national_pokedex_id": 416,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 54, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Vespiquen",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "pachirisu": {
        "national_pokedex_id": 417,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 55, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Pachirisu",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "floatzel": {
        "national_pokedex_id": 419,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 57, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Floatzel",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "cherrim": {
        "national_pokedex_id": 421,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 59, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Cherrim",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gastrodon": {
        "national_pokedex_id": 423,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 61, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gastrodon",
        "pokemon_type": ["water", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "ambipom": {
        "national_pokedex_id": 424,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 64, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Ambipom",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "drifblim": {
        "national_pokedex_id": 426,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 66, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Drifblim",
        "pokemon_type": ["ghost", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "lopunny": {
        "national_pokedex_id": 428,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 68, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Lopunny",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    }, 
    "mismagius": {
        "national_pokedex_id": 429,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 73, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mismagius",
        "pokemon_type": ["ghost"],
        "ability_weakness_modifier": "levitate",
        "version": ["pearl"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "honchkrow": {
        "national_pokedex_id": 430,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 75, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Honchkrow",
        "pokemon_type": ["dark", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["diamond"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "purugly": {
        "national_pokedex_id": 432,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 77, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Purugly",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["pearl"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "purugly (thick fat)": {
        "national_pokedex_id": 432,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 77, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Purugly",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "thick fat",
        "version": ["pearl"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "skuntank": {
        "national_pokedex_id": 435,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 85, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Skuntank",
        "pokemon_type": ["poison", "dark"],
        "ability_weakness_modifier": "none",
        "version": ["diamond"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "bronzong": {
        "national_pokedex_id": 437,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 89, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "bronzong (levitate)": {
        "national_pokedex_id": 437,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 89, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "bronzong (heatproof)": {
        "national_pokedex_id": 437,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 89, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 2,
        "name": "Bronzong",
        "pokemon_type": ["steel", "psychic"],
        "ability_weakness_modifier": "heatproof",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "chatot": {
        "national_pokedex_id": 441,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 102, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Chatot",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "spiritomb": {
        "national_pokedex_id": 442,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 108, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Spiritomb",
        "pokemon_type": ["ghost", "dark"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "garchomp": {
        "national_pokedex_id": 445,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 111, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Garchomp",
        "pokemon_type": ["dragon", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "lucario": {
        "national_pokedex_id": 448,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 116, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Lucario",
        "pokemon_type": ["fighting", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "hippowdon": {
        "national_pokedex_id": 450,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 123, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Hippowdon",
        "pokemon_type": ["ground"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "drapion": {
        "national_pokedex_id": 452,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 128, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Drapion",
        "pokemon_type": ["poison", "dark"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "toxicroak": {
        "national_pokedex_id": 454,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 130, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Toxicroak",
        "pokemon_type": ["poison", "fighting"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "toxicroak (dry skin)": {
        "national_pokedex_id": 454,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 130, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Toxicroak",
        "pokemon_type": ["poison", "fighting"],
        "ability_weakness_modifier": "dry skin",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "carnivine": {
        "national_pokedex_id": 455,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 131, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Carnivine",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "lumineon": {
        "national_pokedex_id": 457,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 135, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Lumineon",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "abomasnow": {
        "national_pokedex_id": 460,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 143, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Abomasnow",
        "pokemon_type": ["grass", "ice"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "weavile": {
        "national_pokedex_id": 461,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 145, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Weavile",
        "pokemon_type": ["dark", "ice"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "magnezone": {
        "national_pokedex_id": 462,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 180, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Magnezone",
        "pokemon_type": ["electric", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "lickilicky": {
        "national_pokedex_id": 463,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 162, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Lickilicky",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "rhyperior": {
        "national_pokedex_id": 464,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 188, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Rhyperior",
        "pokemon_type": ["ground", "rock"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "tangrowth": {
        "national_pokedex_id": 465,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 182, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Tangrowth",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    
    "electivire": {
        "national_pokedex_id": 466,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 199, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Electivire",
        "pokemon_type": ["electric"],
        "ability_weakness_modifier": "motor drive",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "magmortar": {
        "national_pokedex_id": 467,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 202, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Magmortar",
        "pokemon_type": ["fire"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "togekiss": {
        "national_pokedex_id": 468,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 175, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Togekiss",
        "pokemon_type": ["normal", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "yanmega": {
        "national_pokedex_id": 469,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 184, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Yanmega",
        "pokemon_type": ["bug", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "leafeon": {
        "national_pokedex_id": 470,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 169, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Leafeon",
        "pokemon_type": ["grass"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "glaceon": {
        "national_pokedex_id": 471,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 170, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Glaceon",
        "pokemon_type": ["ice"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gliscor": {
        "national_pokedex_id": 472,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 154, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gliscor",
        "pokemon_type": ["ground", "flying"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "mamoswine": {
        "national_pokedex_id": 473,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 205, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mamoswine",
        "pokemon_type": ["ice", "ground"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "porygon-z": {
        "national_pokedex_id": 474,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 194, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Porygon-Z",
        "pokemon_type": ["normal"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "gallade": {
        "national_pokedex_id": 475,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 160, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Gallade",
        "pokemon_type": ["psychic", "fighting"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "probopass": {
        "national_pokedex_id": 476,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 156, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Probopass",
        "pokemon_type": ["rock", "steel"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "dusknoir": {
        "national_pokedex_id": 477,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 191, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Dusknoir",
        "pokemon_type": ["ghost"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": true,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "froslass": {
        "national_pokedex_id": 478,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 208, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Froslass",
        "pokemon_type": ["ice", "ghost"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "rotom": {
        "national_pokedex_id": 479,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 152, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Rotom",
        "pokemon_type": ["electric", "ghost"],
        "ability_weakness_modifier": "levitate",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": false,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "uxie": {
        "national_pokedex_id": 480,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 146, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Uxie",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "mesprit": {
        "national_pokedex_id": 481,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 147, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Mesprit",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "azelf": {
        "national_pokedex_id": 482,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 148, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Azelf",
        "pokemon_type": ["psychic"],
        "ability_weakness_modifier": "levitate",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "dialga": {
        "national_pokedex_id": 483,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 149, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Dialga",
        "pokemon_type": ["steel", "dragon"],
        "ability_weakness_modifier": "none",
        "version": ["diamond", "platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 2,
        "hidden_settings": [false, false, false, false]
    },
    "palkia": {
        "national_pokedex_id": 484,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 150, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Palkia",
        "pokemon_type": ["water", "dragon"],
        "ability_weakness_modifier": "none",
        "version": ["pearl", "platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 2,
        "hidden_settings": [false, false, false, false]
    },
    "giratina": {
        "national_pokedex_id": 487,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 210, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Giratina",
        "pokemon_type": ["ghost", "dragon"],
        "ability_weakness_modifier": "none",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "giratina (origin forme)": {
        "national_pokedex_id": 487,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 210, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 1,
        "name": "Giratina",
        "pokemon_type": ["ghost", "dragon"],
        "ability_weakness_modifier": "levitate",
        "version": ["platinum"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
    "manaphy": {
        "national_pokedex_id": 490,
        "regional_pokedex_id": ["rby", "gsc", "rse", "frlg", 151, "hgss", "bw", "b2w2", "xy", "oras", "sm", "usum", "lgpe", "swsh", "bdsp", "lga", "sv"],
        "variant_id": 0,
        "name": "Manaphy",
        "pokemon_type": ["water"],
        "ability_weakness_modifier": "none",
        "version": ["all"],
        "debut_generation": 4,
        "starter": false,
        "legendary/mythic": true,
        "trade_evolution": false,
        "version_setting_value": 1,
        "hidden_settings": [false, false, false, false]
    },
};